const { app, Menu, Tray, shell, nativeImage } = require("electron");
const archiver = require("archiver");
const { spawn } = require("child_process");
const express = require("express");
const fs = require("fs/promises");
const os = require("os");
const path = require("path");
const crypto = require("crypto");
const PORT=43117, origins=new Set(["https://youtube-frame-capture.vercel.app","http://localhost:3000"]), thresholds={low:.48,normal:.34,high:.22}, jobs=new Map(); let tray;
if(!app.requestSingleInstanceLock()) app.quit(); app.on("open-url",e=>e.preventDefault()); app.on("second-instance",()=>{});
const bin=n=>path.join(process.resourcesPath,"bin",n+(process.platform==="win32"?".exe":""));
const safe=s=>String(s||"youtube-captures").replace(/[<>:"/\\|?*\x00-\x1F]/g,"").trim().slice(0,80)||"youtube-captures";
const stamp=s=>{s=Math.max(0,Math.round(s));return[Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(x=>String(x).padStart(2,"0")).join("-")};
const update=(j,p,s)=>{j.progress=Math.max(j.progress,Math.min(99,Math.round(p)));j.stage=s};
function run(cmd,args,onData){return new Promise((ok,no)=>{const c=spawn(cmd,args,{windowsHide:true});let err="";c.stdout.on("data",x=>onData?.(String(x)));c.stderr.on("data",x=>{x=String(x);err+=x;onData?.(x)});c.on("error",no);c.on("close",code=>code===0?ok():no(new Error(err.slice(-4000))))})}
async function download(j,url,dir,resolution){let json="",err="";const output=path.join(dir,"source.%(ext)s"),height=resolution==="720"?720:resolution==="1080"?1080:2160,format=`bv*[height<=${height}]/bv*`;await new Promise((ok,no)=>{const c=spawn(bin("yt-dlp"),[url,"--dump-single-json","--no-simulate","--no-playlist","--newline","-f",format,"-S",`hdr:sdr,res:${height}`,"--ffmpeg-location",bin("ffmpeg"),"-o",output],{windowsHide:true});c.stdout.on("data",x=>json+=String(x));c.stderr.on("data",x=>{x=String(x);err+=x;const m=x.match(/\[download\]\s+([0-9.]+)%/);if(m)update(j,5+Number(m[1])*.35,"SDR 영상 데이터를 준비하고 있습니다")});c.on("error",no);c.on("close",code=>code===0?ok():no(new Error(err.slice(-4000))))});const name=(await fs.readdir(dir)).find(n=>n.startsWith("source."));if(!name)throw Error("영상 데이터를 찾을 수 없습니다.");let info={};try{info=JSON.parse(json)}catch{}const meta=JSON.stringify([info.dynamic_range,info.format,info.format_note,info.requested_downloads,info.requested_formats]);return{video:path.join(dir,name),title:safe(info.title),duration:Number(info.duration||0),hdr:/HDR|HLG|PQ|Dolby Vision/i.test(meta)}}
function filter(res,hdr){const size={"1080":[1920,1080],"720":[1280,720]}[res];const resize=size?`scale=${size[0]}:${size[1]}:force_original_aspect_ratio=decrease,pad=${size[0]}:${size[1]}:(ow-iw)/2:(oh-ih)/2`:"scale=trunc(iw/2)*2:trunc(ih/2)*2";const color=hdr?"zscale=t=linear:npl=100,format=gbrpf32le,tonemap=mobius,zscale=p=bt709:t=bt709:m=bt709:r=full":"";return[color,resize,"format=rgb24"].filter(Boolean).join(",")}
async function frames(j,r,item,out){const vf=filter(r.resolution,item.hdr),temp=path.join(out,"frame_%03d.png");let logs="",expected=120,select="";if(r.mode==="interval"){expected=Math.min(120,Math.max(1,Math.ceil(item.duration/r.intervalSeconds)));select=`fps=1/${r.intervalSeconds},${vf}`}else{update(j,46,"장면 전환을 분석하며 이미지를 추출하고 있습니다");select=`select='eq(n,0)+gt(scene,${thresholds[r.sensitivity]||.34})',showinfo,${vf}`}await run(bin("ffmpeg"),["-hide_banner","-i",item.video,"-vf",select,"-frames:v","120","-vsync","vfr","-compression_level","3",temp],x=>{logs+=x;const f=[...x.matchAll(/frame=\s*(\d+)/g)].pop();if(f)update(j,45+Math.min(50,Number(f[1])/expected*50),`이미지를 일괄 추출하고 있습니다 (${f[1]})`)});let times=r.mode==="interval"?Array.from({length:expected},(_,i)=>i*r.intervalSeconds):Array.from(logs.matchAll(/pts_time:([0-9.]+)/g),m=>Number(m[1]));const files=(await fs.readdir(out)).filter(n=>/^frame_\d+\.png$/.test(n)).sort();times=times.slice(0,files.length);const result=[];for(let i=0;i<files.length;i++){const time=times[i]||0,name=`capture_${String(i+1).padStart(3,"0")}_${stamp(time)}.png`;await fs.rename(path.join(out,files[i]),path.join(out,name));result.push({filename:name,timestampSeconds:time})}return result}
async function processJob(j,r){try{update(j,2,"영상 정보를 확인하고 있습니다");const item=await download(j,r.url,j.dir,r.resolution);j.title=item.title;update(j,45,"캡처 준비를 하고 있습니다");j.captures=await frames(j,r,item,j.out);j.progress=100;j.stage="완료";j.status="done"}catch(e){j.status="error";j.error=e.message||"처리에 실패했습니다."}}
function server(){const s=express();s.use(express.json({limit:"32kb"}));s.use((q,r,n)=>{const o=q.headers.origin;if(o&&origins.has(o)){r.setHeader("Access-Control-Allow-Origin",o);r.setHeader("Access-Control-Allow-Private-Network","true");r.setHeader("Access-Control-Allow-Headers","content-type");r.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS")}if(q.method==="OPTIONS")return r.sendStatus(204);if(o&&!origins.has(o))return r.sendStatus(403);n()});s.get("/health",(_,r)=>r.json({ok:true,version:app.getVersion()}));s.post("/jobs",async(q,r)=>{const d=q.body||{};if(!/^https?:\/\/(www\.|m\.|music\.)?(youtube\.com|youtu\.be)\//i.test(d.url||""))return r.status(400).json({message:"YouTube URL을 확인해 주세요."});const id=crypto.randomUUID(),dir=await fs.mkdtemp(path.join(os.tmpdir(),"ytcapture-")),out=path.join(dir,"captures");await fs.mkdir(out);const j={id,dir,out,status:"working",progress:0,stage:"시작 중",captures:[],createdAt:Date.now()};jobs.set(id,j);processJob(j,d);r.status(202).json({id})});s.get("/jobs/:id",(q,r)=>{const j=jobs.get(q.params.id);if(!j)return r.sendStatus(404);r.json({status:j.status,progress:j.progress,stage:j.stage,error:j.error,title:j.title,captures:j.captures.map(c=>({...c,imageUrl:`/jobs/${j.id}/images/${encodeURIComponent(c.filename)}`,downloadUrl:`/jobs/${j.id}/files/${encodeURIComponent(c.filename)}`}))})});s.get("/jobs/:id/images/:name",(q,r)=>{const j=jobs.get(q.params.id);if(!j||!j.captures.some(c=>c.filename===q.params.name))return r.sendStatus(404);r.sendFile(path.join(j.out,q.params.name))});s.get("/jobs/:id/files/:name",(q,r)=>{const j=jobs.get(q.params.id);if(!j)return r.sendStatus(404);r.download(path.join(j.out,q.params.name))});s.get("/jobs/:id/download",(q,r)=>{const j=jobs.get(q.params.id);if(!j||j.status!=="done")return r.sendStatus(404);r.attachment(`${j.title}.zip`);const z=archiver("zip",{zlib:{level:4}});z.pipe(r);j.captures.forEach(c=>z.file(path.join(j.out,c.filename),{name:c.filename}));z.finalize()});s.listen(PORT,"127.0.0.1");setInterval(async()=>{for(const[id,j]of jobs)if(Date.now()-j.createdAt>3600000){jobs.delete(id);await fs.rm(j.dir,{recursive:true,force:true})}},600000)}
app.whenReady().then(async()=>{app.setAsDefaultProtocolClient("ytcapture");app.setLoginItemSettings({openAtLogin:true});server();const icon=await app.getFileIcon(process.execPath,{size:"small"});tray=new Tray(icon);tray.setToolTip("YouTube Capture Helper — 실행 중");tray.setContextMenu(Menu.buildFromTemplate([{label:"YouTube Capture Helper 실행 중",enabled:false},{type:"separator"},{label:"웹사이트 열기",click:()=>shell.openExternal("https://youtube-frame-capture.vercel.app")},{label:"프로그램 종료",click:()=>app.quit()}]))});app.on("window-all-closed",e=>e.preventDefault());
